/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** AST parsing result */
export interface AstNode {
  nodeType: string
  startLine: number
  endLine: number
  startColumn: number
  endColumn: number
  text?: string
  children: Array<AstNode>
}
/** Query match result */
export interface QueryMatch {
  pattern: number
  captures: Array<QueryCapture>
}
/** Query capture */
export interface QueryCapture {
  name: string
  text: string
  startLine: number
  endLine: number
}
/**
 * Parse code to AST
 *
 * This is 3-5x faster than WASM Tree-sitter due to:
 * - No FFI overhead between WASM and JavaScript
 * - Native memory management
 * - Direct access to Tree-sitter internals
 */
export declare function parseAst(code: string, languageId: string): string | null
/**
 * Execute Tree-sitter query on code
 *
 * Significantly faster than JavaScript regex for complex patterns
 */
export declare function queryAst(code: string, languageId: string, queryString: string): Array<QueryMatch>
/**
 * Parse multiple files in parallel
 *
 * Uses Rayon for parallel processing - 4-8x faster for large codebases
 */
export declare function parseFilesParallel(files: Array<[string, string]>): Array<string | undefined | null>
/** Clear parser cache (for memory management) */
export declare function clearParserCache(): void
/** Get cache statistics */
export interface CacheStats {
  parsers: number
  languages: number
}
export declare function getCacheStats(): CacheStats
/** Import information */
export interface ImportInfo {
  module: string
  imports: Array<string>
  lineNumber: number
  isDefault: boolean
  isNamespace: boolean
}
/** Function information */
export interface FunctionInfo {
  name: string
  parameters: Array<ParameterInfo>
  returnType?: string
  lineNumber: number
  isAsync: boolean
  isGenerator: boolean
}
/** Parameter information */
export interface ParameterInfo {
  name: string
  paramType?: string
  defaultValue?: string
  isOptional: boolean
}
/** Class information */
export interface ClassInfo {
  name: string
  extends?: string
  implements: Array<string>
  methods: Array<string>
  properties: Array<string>
  lineNumber: number
}
/** Decorator information */
export interface DecoratorInfo {
  name: string
  arguments?: string
  lineNumber: number
  target: string
}
/** Generic type information */
export interface GenericInfo {
  name: string
  constraint?: string
  defaultType?: string
  lineNumber: number
}
/** Semantic analysis result */
export interface SemanticAnalysis {
  imports: Array<ImportInfo>
  functions: Array<FunctionInfo>
  classes: Array<ClassInfo>
  decorators: Array<DecoratorInfo>
  generics: Array<GenericInfo>
}
/**
 * Extract imports from code
 *
 * 5-10x faster than TypeScript regex due to:
 * - Pre-compiled regex patterns
 * - Native string processing
 * - No V8 overhead
 */
export declare function extractImports(code: string, languageId: string): Array<ImportInfo>
/** Extract functions from code */
export declare function extractFunctions(code: string, languageId: string): Array<FunctionInfo>
/** Extract decorators from code */
export declare function extractDecorators(code: string, languageId: string): Array<DecoratorInfo>
/**
 * Perform complete semantic analysis
 *
 * Combines all analysis operations in a single pass for maximum efficiency
 */
export declare function analyzeSemantics(code: string, languageId: string): SemanticAnalysis
/**
 * Token information
 * Token analysis result with Structure of Arrays (SoA) layout for performance
 */
export interface TokenResult {
  texts: Array<string>
  tokenTypes: Array<string>
  starts: Array<number>
  ends: Array<number>
}
/**
 * Tokenize code into tokens
 *
 * Fast tokenization for context building - 2-4x faster than TypeScript
 */
export declare function tokenizeCode(code: string, languageId: string): TokenResult
/**
 * Normalize whitespace in code
 *
 * Fast whitespace normalization using SIMD where available
 */
export declare function normalizeWhitespace(code: string): string
/** Remove comments from code */
export declare function removeComments(code: string, languageId: string): string
/** Count lines of code (excluding comments and blank lines) */
export declare function countLoc(code: string, languageId: string): number
/**
 * Estimate token count for LLM context
 *
 * Fast approximation: ~4 characters per token
 */
export declare function estimateTokens(text: string): number
/**
 * Generate fast hash for cache keys
 *
 * Uses xxHash3 which is 10-20x faster than JavaScript's simple hash
 * and provides excellent distribution for cache keys
 */
export declare function hashPrompt(prompt: string): string
/** Generate hash from multiple strings (for composite keys) */
export declare function hashComposite(parts: Array<string>): string
/** Generate 128-bit hash for extra collision resistance */
export declare function hashPrompt128(prompt: string): string
/** Duplicate code information */
export interface DuplicateInfo {
  text: string
  startLine: number
  endLine: number
  similarity: number
}
/**
 * Detect duplicate code segments
 *
 * Uses rolling hash and SIMD string comparison for 4-8x speedup
 */
export declare function detectDuplicates(code: string, context: string, minLength?: number | undefined | null): Array<DuplicateInfo>
/** Fast substring search using SIMD */
export declare function findSubstring(haystack: string, needle: string): number | null
/** Find all occurrences of a pattern */
export declare function findAllOccurrences(haystack: string, needle: string): Array<number>
/** Initialize the native module */
export declare function init(): string
/** Get module version */
export declare function getVersion(): string
/** Check if native module is available */
export declare function isAvailable(): boolean
/**
 * Streaming hash for large inputs
 *
 * Useful for hashing large files without loading entirely into memory
 */
export declare class StreamingHasher {
  constructor()
  update(data: string): void
  digest(): string
  digest128(): string
  reset(): void
}
