# ESLint Configuration for Inline Extension

root: true

env:
  node: true
  es2021: true

parser: '@typescript-eslint/parser'

parserOptions:
  ecmaVersion: 2021
  sourceType: module
  project: './tsconfig.json'

plugins:
  - '@typescript-eslint'

extends:
  - 'eslint:recommended'
  - 'plugin:@typescript-eslint/recommended'

rules:
  '@typescript-eslint/no-explicit-any': 'warn'
  '@typescript-eslint/explicit-module-boundary-types': 'off'
  '@typescript-eslint/no-unused-vars':
    - 'warn'
    - argsIgnorePattern: '^_'
  'no-console': 'off'
  'semi': ['error', 'always']
  'quotes': ['error', 'single', { avoidEscape: true }]

ignorePatterns:
  - 'out'
  - 'node_modules'
  - '.vscode-test'
  - 'test/fixtures'
